#!/bin/bash
# arch-test-03 configuration
DRIVE=/dev/sda
BOOT_MB=2048
SWAP_MB=4096
ROOT_MB=10240
TIMEZONE="US/Pacific"
LANG="en_US.UTF-8"
KEYMAP="us"
HOSTNAME="arch-test-03.socketwrench.net"
TESTURL="archlinux.org"
packages=("base" "linux" "linux-firmware" "lvm2" "grub" "efibootmgr" "networkmanager" "vi" "openssh" "sshpass")
hooks=("base" "systemd" "udev" "autodetect" "microcode" "modconf" "kms" "keyboard" "keymap" "consolefont" "block" "lvm2" "filesystems" "fsck")
modules=("")
grubcmdlinedefault=("loglevel=3")
