#!/bin/bash
# wrenchbox configuration variables
DRIVE=/dev/nvme0n1
BOOT_MB=2048
SWAP_MB=32768
ROOT_MB=1048576
TIMEZONE="US/Pacific"
LANG="en_US.UTF-8"
FONT="lat2-16"
KEYMAP="us"
HOSTNAME="wrenchbox.socketwrench.net"
TESTURL="archlinux.org"
packages=("base" "linux" "linux-firmware" "lvm2" "grub" "efibootmgr" "networkmanager" "vi" "vim" "openssh" "sshpass" "python" "parted")
hooks=("base" "systemd" "udev" "autodetect" "microcode" "modconf" "kms" "keyboard" "keymap" "consolefont" "block" "lvm2" "filesystems" "fsck")
modules=("vfio" "vfio_pci" "vfio_iommu_type1")
grubcmdlinedefault=("loglevel=3")
